name: Build e Deploy do Front-End

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar o repositório
        uses: actions/checkout@v3

      - name: 2. Simular build (validação dos arquivos)
        run: |
          echo "Validando arquivos..."
          ls -la
          file index.html styles.css script.js

      - name: 3. Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
